# Generated by Django 4.2 on 2024-03-30 17:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=32)),
                ('last_name', models.CharField(blank=True, default='', max_length=32)),
                ('patronymic', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('birthday', models.DateField(max_length=32)),
                ('connection_address', models.CharField(max_length=16)),
                ('client_type', models.CharField(choices=[('individuall', 'физическое лицо'), ('legal', 'юридическое лицо')], max_length=128)),
                ('status', models.CharField(choices=[('connecting', 'подключение'), ('active', 'активный'), ('blocked', 'заблокирован'), ('annulled', 'рассторгнут'), ('stopped', 'приостановлено')], max_length=128)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('limit', models.DecimalField(decimal_places=2, default=30000, max_digits=10)),
                ('department', models.CharField(max_length=128)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('qr', 'QR-код'), ('auto', 'Автоплатеж'), ('bank', 'Банковский платеж'), ('cash', 'Наличными'), ('card', 'Картой'), ('post', 'Почта России'), ('Sber', 'Сбер-онлайн'), ('SBP', 'СПБ')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_cycle', models.BooleanField(default=False)),
                ('period', models.CharField(blank=True, default='1 m', max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.client')),
                ('services', models.ForeignKey(default='Услуга', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='expenses', to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expense')),
            ],
            options={
                'unique_together': {('client', 'expense', 'is_paid')},
            },
        ),
    ]
