# Generated by Django 4.2 on 2024-03-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('connecting', 'подключение'), ('active', 'активный'), ('blocked', 'заблокирован'), ('annulled', 'рассторгнут'), ('stopped', 'приостановлено')], max_length=128),
        ),
    ]
