# Generated by Django 5.0.3 on 2024-03-30 05:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_client_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individuall', 'физическое лицо'), ('legal', 'юридическое лицо')], max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('connecting', 'подключение'), ('active', 'активный'), ('blocked', 'заблокирован'), ('annulled', 'рассторгнут'), ('stopped', 'приостановлено')], max_length=128),
        ),
        migrations.AlterField(
            model_name='expense',
            name='services',
            field=models.ForeignKey(default='service', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='expenses', to='api.service'),
        ),
    ]
