# Generated by Django 5.0.3 on 2024-03-30 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_service_client_last_update_alter_client_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(max_length=32),
        ),
        migrations.AlterField(
            model_name='client',
            name='connection_address',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='expense',
            name='services',
            field=models.ForeignKey(default='Услуга', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='expenses', to='api.service'),
        ),
    ]
